# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonlink',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='lessonlink',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
