# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_course', '0002_auto_20161206_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('identifier', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
