# Generated by Django 2.0.5 on 2019-01-15 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('python_course_2', '0002_timetablealteration_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablealteration',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
