# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_itself', models.FileField(upload_to='')),
                ('name', models.CharField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('upload_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
